env:
  SYSDIG_URL: "https://app.us4.sysdig.com/"
  APP_NAME: "brett-tko"
  REGISTRY: "ghcr.io"
  
name: tko

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Get the version (or use any other method)
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Docker metadata tag set (or use some another method)
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.APP_NAME }}
        tags: |
          type=raw,priority=100,enable=${{ github.event_name == 'push' }},value=${{ steps.get_version.outputs.VERSION }}
        labels: |
          org.opencontainers.image.title=${{ env.APP_NAME }}

    - name: Get the Current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Get the New Scanner
      run: curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"

    - name: Make the New Scanner executable
      run: chmod +x ./sysdig-cli-scanner


    - name: Scan Image with New Scanner
      env:
        SECURE_API_TOKEN: ${{ secrets.SYSDIG_API_TOKEN }}
      run: ./sysdig-cli-scanner --apiurl ${{ env.SYSDIG_URL }} ${{ env.APP_NAME }}:bld-${{ steps.date.outputs.date }}
