name: "brett-tko"

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
env:
  SYSDIG_URL: "https://app.us4.sysdig.com/"
  APP_NAME: "brett-tko"
  REGISTRY: "ghcr.io"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Get the version (or use any other method)
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Docker metadata tag set (or use some another method)
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.APP_NAME }}
        tags: |
          type=raw,priority=100,enable=${{ github.event_name == 'push' }},value=${{ steps.get_version.outputs.VERSION }}
        labels: |
          org.opencontainers.image.title=${{ env.APP_NAME }}

    - name: Get the Current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  
    - name: Build
      run: docker build . -t ${{ env.APP_NAME }}:bld-${{ steps.date.outputs.date }}
        
    - name: Get the New Scanner
      run: curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"

    - name: Make the New Scanner executable
      run: chmod +x ./sysdig-cli-scanner

    - name: Scan Image with New Scanner
      env:
        SECURE_API_TOKEN: ${{ secrets.TTT }}
      run: ./sysdig-cli-scanner --apiurl ${{ env.SYSDIG_URL }} ${{ env.APP_NAME }}:bld-${{ steps.date.outputs.date }}

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: surefire-reports
        path: /home/runner/work/tko-brett/tko-brett/scan-logs/**

    - name: re-tag
      run: docker tag ${{ env.APP_NAME }}:bld-${{ steps.date.outputs.date }} ${{ env.REGISTRY }}/bwolmarans/tko-brett/${{ env.APP_NAME }}:bld-${{ steps.date.outputs.date }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: bwolmarans
        password: ${{ secrets.REGISTRY_PASSWORD }}
          
    - name: push-finally
      run: docker push ${{ env.REGISTRY }}/bwolmarans/tko-brett/${{ env.APP_NAME }}:bld-${{ steps.date.outputs.date }}
      
    
